name: Release Build

on:
  push:
    branches:
      - release

jobs:
  deploy:
    uses: DomeHQ/cards-ci/.github/workflows/card-release.yml@stable
    secrets:
      WEBAPP_DEPLOY_TOKEN: ${{ secrets.WEBAPP_DEPLOY_TOKEN }}
      CARD_DEC_BLOB: ${{ secrets.CARD_DEC_BLOB }}
      VITE_GROQ_API_KEY: ${{ secrets.VITE_GROQ_API_KEY }}
